### ISSUE TITLE
On send message, keep keyboard opened

### ISSUE THREAD

**Issue by tjerman** [crusttech/mobile-messaging.hybrid#8]
Currently, it closes, and I find it quite annoying. Should it behave as it does now, or do we do a switch (I vote for the latter :wink:)

**Comment by zmija** [comment]
Sure, go ahead.

**Comment by tjerman** [comment]
Implemented in https://github.com/cortezaproject/corteza-webapp-messaging/commit/a31322f14865954bada503e1f83c3e76a06f7508

I've also applied a few tweaks, such as disabling the send message button if the message is invalid (empty/only \n), removing emoji picker button
